### ISSUE TITLE
muxrpc client crashes when go-ssb-room closes or something

### ISSUE THREAD

**Issue by staltz** [ssb-ngi-pointer/go-ssb-room#190]
## Reproduction steps

- Alice uses Manyverse to connect to hermies.club
- Alice is connect to other peers there via tunnel.connect
- hermies.club got hard-restarted to update its code
- Alice's Manyverse crashes with the error below:

```
{ name: 'Error', message: 'muxrpc: session terminated', stack: '' }
```

Not a lot more info is given, no stacktrace or anything. It might be a bug in JS ssb-conn (or muxrpc or elsewhere), but at least it would be good to know exactly what causes this.

**Comment by cryptix** [comment]
Some thoughts: https://github.com/ssb-ngi-pointer/go-ssb-room/issues/170#issuecomment-823423171

**Comment by staltz** [comment]
I'm keeping my manyverse open and connected to hermies.club and this crash occurs frequently. I got another log this time, and it has more useful information:

```
04-22 20:08:22.240 26309 26555 E NODEJS-MOBILE: 2021-04-22T17:08:22.240Z ssb:room-client we wish to connect to { name: 'tunnel', portal: '@uMYDVPuEKftL4SzpRGVyQxLdyPkOiX7njit7+qT/7IQ=.ed25519', target: '@p13zSAiOpguI9nsawkGijsnMfWmFd5rlUNpzekEE+vI=.ed25519' }
04-22 20:08:22.240 26309 26555 E NODEJS-MOBILE: 2021-04-22T17:08:22.240Z ssb:room-client will call tunnel.connect at @p13zSAiOpguI9nsawkGijsnMfWmFd5rlUNpzekEE+vI=.ed25519 via room @uMYDVPuEKftL4SzpRGVyQxLdyPkOiX7njit7+qT/7IQ=.ed25519
04-22 20:08:22.529 26309 26555 E NODEJS-MOBILE: 2021-04-22T17:08:22.528Z ssb:room-client got endpoints from @uMYDVPuEKftL4SzpRGVyQxLdyPkOiX7njit7+qT/7IQ=.ed25519: ["@+UMKhpbzXAII+2/7ZlsgkJwIsxdfeFi36Z5Rk1gCfY0=.ed25519","@2RNGJafZtMHzd76gyvqH6EJiK7kBnXeak5mBWzoO/iU=.ed25519","@BQXNdakpRpHqxDP2QZP/RJr95osWzW+q89MXYOZJpzw=.ed25519","@MRiJ+CvDnD9ZjqunY1oy6tsk0IdbMDC4Q3tTC8riS3s=.ed25519","@qv10rF4IsmxRZb7g5ekJ33EakYBpdrmV/vtP1ij5BS4=.ed25519"]
04-22 20:08:22.533 26309 26555 E NODEJS-MOBILE: 2021-04-22T17:08:22.532Z ssb:room-client will conn.stage("tunnel:@uMYDVPuEKftL4SzpRGVyQxLdyPkOiX7njit7+qT/7IQ=.ed25519:@BQXNdakpRpHqxDP2QZP/RJr95osWzW+q89MXYOZJpzw=.ed25519~shs:BQXNdakpRpHqxDP2QZP/RJr95osWzW+q89MXYOZJpzw=")
04-22 20:08:22.536 26309 26555 E NODEJS-MOBILE: 2021-04-22T17:08:22.536Z ssb:room-client will conn.stage("tunnel:@uMYDVPuEKftL4SzpRGVyQxLdyPkOiX7njit7+qT/7IQ=.ed25519:@qv10rF4IsmxRZb7g5ekJ33EakYBpdrmV/vtP1ij5BS4=.ed25519~shs:qv10rF4IsmxRZb7g5ekJ33EakYBpdrmV/vtP1ij5BS4=")
04-22 20:08:22.540 26309 26555 E NODEJS-MOBILE: 2021-04-22T17:08:22.540Z ssb:room-client got endpoints from @uMYDVPuEKftL4SzpRGVyQxLdyPkOiX7njit7+qT/7IQ=.ed25519: ["@+UMKhpbzXAII+2/7ZlsgkJwIsxdfeFi36Z5Rk1gCfY0=.ed25519","@2RNGJafZtMHzd76gyvqH6EJiK7kBnXeak5mBWzoO/iU=.ed25519","@BQXNdakpRpHqxDP2QZP/RJr95osWzW+q89MXYOZJpzw=.ed25519","@MRiJ+CvDnD9ZjqunY1oy6tsk0IdbMDC4Q3tTC8riS3s=.ed25519","@qv10rF4IsmxRZb7g5ekJ33EakYBpdrmV/vtP1ij5BS4=.ed25519"]
04-22 20:08:22.544 26309 26555 E NODEJS-MOBILE: 2021-04-22T17:08:22.544Z ssb:room-client will conn.stage("tunnel:@uMYDVPuEKftL4SzpRGVyQxLdyPkOiX7njit7+qT/7IQ=.ed25519:@BQXNdakpRpHqxDP2QZP/RJr95osWzW+q89MXYOZJpzw=.ed25519~shs:BQXNdakpRpHqxDP2QZP/RJr95osWzW+q89MXYOZJpzw=")
04-22 20:08:22.552 26309 26555 E NODEJS-MOBILE: 2021-04-22T17:08:22.552Z ssb:room-client will conn.stage("tunnel:@uMYDVPuEKftL4SzpRGVyQxLdyPkOiX7njit7+qT/7IQ=.ed25519:@qv10rF4IsmxRZb7g5ekJ33EakYBpdrmV/vtP1ij5BS4=.ed25519~shs:qv10rF4IsmxRZb7g5ekJ33EakYBpdrmV/vtP1ij5BS4=")
04-22 20:08:22.559 26309 26555 E NODEJS-MOBILE: Error: stackless error
04-22 20:08:22.559 26309 26555 E NODEJS-MOBILE:     at module.exports (/data/data/se.manyver/files/nodejs-project/index.js:64002:19)
04-22 20:08:22.559 26309 26555 E NODEJS-MOBILE:     at abort (/data/data/se.manyver/files/nodejs-project/index.js:22518:45)
04-22 20:08:22.559 26309 26555 E NODEJS-MOBILE:     at Object.cb (/data/data/se.manyver/files/nodejs-project/index.js:22533:26)
04-22 20:08:22.559 26309 26555 E NODEJS-MOBILE:     at drain (/data/data/se.manyver/files/nodejs-project/index.js:38975:23)
04-22 20:08:22.559 26309 26555 E NODEJS-MOBILE:     at /data/data/se.manyver/files/nodejs-project/index.js:38992:18
04-22 20:08:22.559 26309 26555 E NODEJS-MOBILE:     at /data/data/se.manyver/files/nodejs-project/index.js:38949:7
04-22 20:08:22.559 26309 26555 E NODEJS-MOBILE:     at PacketStreamSubstream.weird.read (/data/data/se.manyver/files/nodejs-project/index.js:39626:7)
04-22 20:08:22.559 26309 26555 E NODEJS-MOBILE:     at PacketStream._onstream (/data/data/se.manyver/files/nodejs-project/index.js:3463:12)
04-22 20:08:22.559 26309 26555 E NODEJS-MOBILE:     at PacketStream.write (/data/data/se.manyver/files/nodejs-project/index.js:3397:41)
04-22 20:08:22.559 26309 26555 E NODEJS-MOBILE:     at /data/data/se.manyver/files/nodejs-project/index.js:39649:15
04-22 20:08:22.561 26309 26555 E NODEJS-MOBILE: Error: stackless error
04-22 20:08:22.561 26309 26555 E NODEJS-MOBILE:     at module.exports (/data/data/se.manyver/files/nodejs-project/index.js:64002:19)
04-22 20:08:22.561 26309 26555 E NODEJS-MOBILE:     at abort (/data/data/se.manyver/files/nodejs-project/index.js:22518:45)
04-22 20:08:22.561 26309 26555 E NODEJS-MOBILE:     at Object.cb (/data/data/se.manyver/files/nodejs-project/index.js:22525:24)
04-22 20:08:22.561 26309 26555 E NODEJS-MOBILE:     at drain (/data/data/se.manyver/files/nodejs-project/index.js:38975:23)
04-22 20:08:22.561 26309 26555 E NODEJS-MOBILE:     at /data/data/se.manyver/files/nodejs-project/index.js:38992:18
04-22 20:08:22.561 26309 26555 E NODEJS-MOBILE:     at /data/data/se.manyver/files/nodejs-project/index.js:38949:7
04-22 20:08:22.561 26309 26555 E NODEJS-MOBILE:     at PacketStreamSubstream.weird.read (/data/data/se.manyver/files/nodejs-project/index.js:39626:7)
04-22 20:08:22.561 26309 26555 E NODEJS-MOBILE:     at PacketStream._onstream (/data/data/se.manyver/files/nodejs-project/index.js:3463:12)
04-22 20:08:22.561 26309 26555 E NODEJS-MOBILE:     at PacketStream.write (/data/data/se.manyver/files/nodejs-project/index.js:3397:41)
04-22 20:08:22.561 26309 26555 E NODEJS-MOBILE:     at /data/data/se.manyver/files/nodejs-project/index.js:39649:15
04-22 20:08:22.645 26309 26555 E NODEJS-MOBILE: { name: 'Error', message: 'muxrpc: session terminated', stack: '' }
04-22 20:08:22.648 26309 26555 E NODEJS-MOBILE: 2021-04-22T17:08:22.648Z ssb:conn-hub failed to connect to tunnel:@uMYDVPuEKftL4SzpRGVyQxLdyPkOiX7njit7+qT/7IQ=.ed25519:@p13zSAiOpguI9nsawkGijsnMfWmFd5rlUNpzekEE+vI=.ed25519~shs:p13zSAiOpguI9nsawkGijsnMfWmFd5rlUNpzekEE+vI=
04-22 20:08:22.652 26309 26555 E NODEJS-MOBILE: 2021-04-22T17:08:22.651Z ssb:conn-hub failed to connect to tunnel:@uMYDVPuEKftL4SzpRGVyQxLdyPkOiX7njit7+qT/7IQ=.ed25519:@2RNGJafZtMHzd76gyvqH6EJiK7kBnXeak5mBWzoO/iU=.ed25519~shs:2RNGJafZtMHzd76gyvqH6EJiK7kBnXeak5mBWzoO/iU=
04-22 20:08:22.745 26309 26555 E NODEJS-MOBILE: terminating with uncaught exception of type std::__ndk1::system_error: mutex lock failed: Device or resource busy
```

I'm still going to carefully parse all of that dump, but here's some highlights:

- Notice the tunnel.connect to `@p13z` (cryptix) at the top, right before the stackless errors appear
- We get `stackless error` as well as 'muxrpc: session terminated'
- The `stackless error` points to secret-handshake `abort` and PacketStream, I'll parse that properly later
- The actual crash is related to `std::__ndk1::system_error mutex lock failed: Device or resource busy` which is from c++

My hunch is that the JS communicates something to the Go, and the Go considers that data or scenario to be invalid which causes an error to be sent to JS, which to JS is one of these unhandled scenarios that never occurred with ssb-room (JS). Actually, I believe that every time we get a stackless error, it's coming from Go, probably because the JS stack dominic built is transferring JS stack traces *between* peers.

**Comment by staltz** [comment]
This one wasn't a crash, but might be related. And by the way, I think all these issues are happening only with `@p13z` over tunnels

```
[ 04-22 20:46:20.325 23363:23674 E/NODEJS-MOBILE ]
2021-04-22T17:46:20.325Z ssb:room-client we wish to connect to { name: 'tunnel', portal: '@uMYDVPuEKftL4SzpRGVyQxLdyPkOiX7njit7+qT/7IQ=.ed25519', target: '@p13zSAiOpguI9nsawkGijsnMfWmFd5rlUNpzekEE+vI=.ed25519' }

[ 04-22 20:46:20.325 23363:23674 E/NODEJS-MOBILE ]
2021-04-22T17:46:20.325Z ssb:room-client will call tunnel.connect at @p13zSAiOpguI9nsawkGijsnMfWmFd5rlUNpzekEE+vI=.ed25519 via room @uMYDVPuEKftL4SzpRGVyQxLdyPkOiX7njit7+qT/7IQ=.ed25519

[ 04-22 20:46:25.338 23363:23674 E/NODEJS-MOBILE ]
2021-04-22T17:46:25.338Z ssb:conn-hub failed to connect to tunnel:@uMYDVPuEKftL4SzpRGVyQxLdyPkOiX7njit7+qT/7IQ=.ed25519:@p13zSAiOpguI9nsawkGijsnMfWmFd5rlUNpzekEE+vI=.ed25519~shs:p13zSAiOpguI9nsawkGijsnMfWmFd5rlUNpzekEE+vI=

[ 04-22 20:46:25.377 23363:23613 E/ReactNativeJS ]
shs.client: error when expecting server to accept challenge (phase 1).
possibly the server is busy, does not speak shs or uses a different application cap
```

**Comment by staltz** [comment]
I also got this strange error (notice `~shs:____` where `____` is absence of the public key)

```
[ 04-22 21:19:57.694 12577:12935 E/NODEJS-MOBILE ]
server error, from tunnel:@uMYDVPuEKftL4SzpRGVyQxLdyPkOiX7njit7+qT/7IQ=.ed25519:@qv10rF4IsmxRZb7g5ekJ33EakYBpdrmV/vtP1ij5BS4=.ed25519~shs:

[ 04-22 21:19:57.694 12577:12935 E/NODEJS-MOBILE ]

```

**Comment by staltz** [comment]
Another error I got, which is not a crash:

```
no stream for incoming msg {
  req: -56,
  stream: true,
  end: true,
  value: {
    message: 'shs.client: error when expecting server to accept challenge (phase 1).\n' +
      'possibly the server is busy, does not speak shs or uses a different application cap',
    name: 'Error',
    stack: 'Error: shs.client: error when expecting server to accept challenge (phase 1).\n' +
      'possibly the server is busy, does not speak shs or uses a different application cap\n' +
      '    at abort (/home/staltz/oss/patchwork/node_modules/secret-handshake/protocol.js:37:45)\n' +
      '    at Object.cb (/home/staltz/oss/patchwork/node_modules/secret-handshake/protocol.js:44:24)\n' +
      '    at drain (/home/staltz/oss/patchwork/node_modules/pull-reader/index.js:46:23)\n' +
      '    at /home/staltz/oss/patchwork/node_modules/pull-reader/index.js:63:18\n' +
      '    at source (/home/staltz/oss/patchwork/node_modules/muxrpc/pull-weird.js:44:9)\n' +
      '    at /home/staltz/oss/patchwork/node_modules/pull-reader/index.js:16:7\n' +
      '  Error: pull-reader: read exceeded timeout\n' +
      '    at /home/staltz/oss/patchwork/node_modules/pull-reader/index.js:16:10'
  },
  length: 978,
  type: 2
}
```

Notice the last part, `pull-reader: read exceeded timeout`, I think it comes from pull-handshake: https://github.com/pull-stream/pull-handshake/blob/1deaa884db13a259de6c4b9c4768d00251a39e70/index.js#L21

**Comment by staltz** [comment]
**Okay** I emerge from debugging with some meaningful conclusions:

## Conclusion 1

:arrow_right: `stackless error` indicates something from Go. On one hand it's comforting to narrow down the error, because we know for sure it comes interacting with Go, on the other hand sometimes JS modules print *only* `err.stack` leaving us with no information.

https://github.com/cryptoscope/go-muxrpc/blob/721bf2d721a9170cbc79be93de66f144a6413a2d/stream.go#L104-L105

https://github.com/cryptoscope/go-muxrpc/blob/721bf2d721a9170cbc79be93de66f144a6413a2d/errors.go#L23-L25


## Conclusion 2

:arrow_right:  `muxrpc: session terminated` is the Go equivalent of JS's `unexpected end of parent stream`

| Go | JS |
|----|----|
| https://github.com/cryptoscope/go-muxrpc/blob/721bf2d721a9170cbc79be93de66f144a6413a2d/rpc_server.go#L470-L475 | https://github.com/ssbc/packet-stream/blob/bb0493dd0eb6454ac675df78dfed20e994a4881f/index.js#L63-L64 |

## Conclusion 3

:arrow_right: Both Go and JS consider `unexpected end of parent stream` to be a "clean and correct end" not a failure case.

| Go | JS |
|----|----|
| https://github.com/cryptoscope/go-muxrpc/blob/721bf2d721a9170cbc79be93de66f144a6413a2d/errors.go#L73-L75 | https://github.com/ssbc/ssb-replicate/blob/6c683f61edb1aacb11cbbcbc0d1c4561311737f1/legacy.js#L276-L283 |

## Actionable conclusion 4

:arrow_right: Perhaps JS should treat `muxrpc: session terminated` as a clean and correct end, not a failure.

:arrow_right: Perhaps Go should rename `muxrpc: session terminated` to `unexpected end of parent stream` so that we have a standard way of signalling clean and correct ends. Should this be part of a spec?

:arrow_right: ssb-replicate/legacy [handles all sorts of errors](https://github.com/ssbc/ssb-replicate/blob/6c683f61edb1aacb11cbbcbc0d1c4561311737f1/legacy.js#L21-L32) but we don't seem to do this error handling elsewhere (like ssb-ebt or in other cases where we connect to a remote peer but don't replicate with them, which is the case of connecting to a room before doing any tunnels).

**Comment by cryptix** [comment]
Found a reproduction with [this gist](https://gist.github.com/cryptix/4ae17707f99b97f31161804956fa5d75).

`pull.drain(cb)` (without a 2nd done callback) considered harmful, on RPCs at least.

**Comment by staltz** [comment]
Updating ssb-room-client, now instead of crashing, it logs

```
2021-04-26T11:44:59.596Z ssb:room-client error getting updates from room 
@uMYDVPuEKftL4SzpRGVyQxLdyPkOiX7njit7+qT/7IQ=.ed25519 because muxrpc: session terminated
```

:100: :sunglasses:

**Comment by staltz** [comment]
And I fixed Manyverse's error handling to do the same 

```
                throw end
                ^
```

as the gist was doing. In Manyverse I had put some code to catch all JS exceptions so that they are reported to GitLab, but it was doing something funky. Funk removed, but crash reporting to GitLab still preserved. :100:

**Comment by staltz** [comment]
As far as I'm concerned, this bug is now solved. I'll let you press the Close button when you find appropriate though.
