### ISSUE TITLE
Failing to connect with shs errors when receiving new clients

### ISSUE THREAD

**Issue by staltz** [ssb-ngi-pointer/go-ssb-room#202]
I opened Manyverse which tried to connect only to hermies.club, and Manyverse got these logs

```
2021-04-26T11:38:48.925Z ssb:conn-hub failed to connect to net:hermies.club:8008~shs:
uMYDVPuEKftL4SzpRGVyQxLdyPkOiX7njit7+qT/7IQ= because: shs.client: error when expecting 
server to accept challenge (phase 1).
possibly the server is busy, does not speak shs or uses a different application cap

2021-04-26T11:38:56.031Z ssb:conn-hub connecting to net:hermies.club:8008~shs:
uMYDVPuEKftL4SzpRGVyQxLdyPkOiX7njit7+qT/7IQ=

2021-04-26T11:39:01.136Z ssb:conn-hub failed to connect to net:hermies.club:8008~shs:
uMYDVPuEKftL4SzpRGVyQxLdyPkOiX7njit7+qT/7IQ= because: shs.client: error when expecting 
server to accept challenge (phase 1).
possibly the server is busy, does not speak shs or uses a different application cap

2021-04-26T11:39:08.248Z ssb:conn-hub connecting to net:hermies.club:8008~shs:
uMYDVPuEKftL4SzpRGVyQxLdyPkOiX7njit7+qT/7IQ=

2021-04-26T11:39:13.349Z ssb:conn-hub failed to connect to net:hermies.club:8008~shs:
uMYDVPuEKftL4SzpRGVyQxLdyPkOiX7njit7+qT/7IQ= because: shs.client: error when expecting 
server to accept challenge (phase 1).
possibly the server is busy, does not speak shs or uses a different application cap

2021-04-26T11:39:20.164Z ssb:conn-hub connecting to net:hermies.club:8008~shs:
uMYDVPuEKftL4SzpRGVyQxLdyPkOiX7njit7+qT/7IQ=

2021-04-26T11:39:25.471Z ssb:conn-hub failed to connect to net:hermies.club:8008~shs:
uMYDVPuEKftL4SzpRGVyQxLdyPkOiX7njit7+qT/7IQ= because: shs.client: error when expecting 
server to accept challenge (phase 1).
possibly the server is busy, does not speak shs or uses a different application cap
```

I then restarted the server with `systemctl` and then the connection in Manyverse succeeded as expected.

Ideally, we wouldn't need a server restart and we clients wouldn't see the `shs` error upon connecting.

**Comment by staltz** [comment]
It also happens with other room attendants:

```
[ 04-26 17:33:23.505  2802: 2890 E/NODEJS-MOBILE ]
2021-04-26T14:33:23.505Z ssb:room-client we wish to connect to { name: 'tunnel', portal: 
'@uMYDVPuEKftL4SzpRGVyQxLdyPkOiX7njit7+qT/7IQ=.ed25519', target: 
'@VIOn+8a/vaQvv/Ew3+KriCngyUXHxHbjXkj4GafBAY0=.ed25519' }
2021-04-26T14:33:23.505Z ssb:room-client will call tunnel.connect at 
@VIOn+8a/vaQvv/Ew3+KriCngyUXHxHbjXkj4GafBAY0=.ed25519 via room 
@uMYDVPuEKftL4SzpRGVyQxLdyPkOiX7njit7+qT/7IQ=.ed25519

[ 04-26 17:33:28.509  2802: 2890 E/NODEJS-MOBILE ]
2021-04-26T14:33:28.509Z ssb:room-client tunnel duplex broken with { name: 'tunnel', 
portal: '@uMYDVPuEKftL4SzpRGVyQxLdyPkOiX7njit7+qT/7IQ=.ed25519', target: 
'@VIOn+8a/vaQvv/Ew3+KriCngyUXHxHbjXkj4GafBAY0=.ed25519' } because 
shs.client: error when expecting server to accept challenge (phase 1).
possibly the server is busy, does not speak shs or uses a different application cap
```

**Comment by staltz** [comment]
The JS error masked by `shs.client: error ...` is:

```
Error: pull-reader: read exceeded timeout
    at Timeout._onTimeout (/data/data/se.manyver/files/nodejs-project/index.js:37667:10)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

**Comment by staltz** [comment]
This may turn out to not be about go-ssb-room! In the past 30min I've been connected to only JS rooms, and I detected a few (although it happened more often with go-ssb-room):

```
Error: pull-reader: read exceeded timeout 5000
    at Timeout._onTimeout (/data/data/se.manyver/files/nodejs-project/index.js:37667:10)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)

2021-04-26T15:49:43.953Z ssb:room-client tunnel duplex broken with { name: 'tunnel', portal: '@W18NyiHagiiVE4/jm2sxzqQqIwmUw2p9pKZ0lHH9OXA=.ed25519', target: '@THUzexG1y6kWofwiN8Lix/jNH/P6roYdlCDgpAn2HSc=.ed25519' } because shs.client: error when expecting server to accept challenge (phase 1).
possibly the server is busy, does not speak shs or uses a different application cap

2021-04-26T15:49:43.955Z ssb:conn-hub failed to connect to tunnel:@W18NyiHagiiVE4/jm2sxzqQqIwmUw2p9pKZ0lHH9OXA=.ed25519:@THUzexG1y6kWofwiN8Lix/jNH/P6roYdlCDgpAn2HSc=.ed25519~shs:THUzexG1y6kWofwiN8Lix/jNH/P6roYdlCDgpAn2HSc= because: shs.client: error when expecting server to accept challenge (phase 1).
possibly the server is busy, does not speak shs or uses a different application cap

shs.client: error when expecting server to accept challenge (phase 1).
possibly the server is busy, does not speak shs or uses a different application cap

no stream for incoming msg {
  req: -11,
  stream: true,
  end: true,
  value: {
    message: 'shs.client: error when expecting server to accept challenge (phase 1).\n' +
      'possibly the server is busy, does not speak shs or uses a different application cap',
    name: 'Error',
    stack: 'Error: shs.client: error when expecting server to accept challenge (phase 1).\n' +
      'possibly the server is busy, does not speak shs or uses a different application cap\n' +
      '    at abort (/data/data/se.manyver/files/nodejs-project/index.js:19583:45)\n' +
      '    at Object.cb (/data/data/se.manyver/files/nodejs-project/index.js:19592:24)\n' +
      '    at drain (/data/data/se.manyver/files/nodejs-project/index.js:37697:23)\n' +
      '    at /data/data/se.manyver/files/nodejs-project/index.js:37714:18\n' +
      '    at source (/data/data/se.manyver/files/nodejs-project/index.js:38359:9)\n' +
      '    at Timeout._onTimeout (/data/data/se.manyver/files/nodejs-project/index.js:37667:7)\n' +
      '  Error: pull-reader: read exceeded timeout 5000\n' +
      '    at Timeout._onTimeout (/data/data/se.manyver/files/nodejs-project/index.js:37667:10)\n' +
      '    at listOnTimeout (internal/timers.js:554:17)\n' +
      '    at processTimers (internal/timers.js:497:7)'
  },
  length: 1066,
  type: 2
```

**Comment by staltz** [comment]
One hypothesis, although I wouldn't assign too much probability to it: this could be one of those deweird-territory bugs, because deweird bugs occurred when an implementation was fast (in the case of ssb-db2 it was the raw log stream that was the fastest one). That would explain why this issue occurs more frequently with go-ssb-room than with JS room, because Go is faster. But I don't see exactly where this would happen, because it would have to be a `source` muxrpc somewhere between the tunnels. (Or maybe `duplex` muxrpcs also suffer from deweird bugs)

But this hypothesis explains only tunnel connection bugs between attendants, doesn't explain the bug where the client cannot connect to the go-ssb-room.

**Comment by staltz** [comment]
Another hypothesis, a pretty good one I think: I updated ssb-room-client to 0.13.0 on my own phone, but the other attendants in hermies.club haven't yet updated theirs, so it's not like the bug #190 is entirely gone, it may look different from my side.

This doesn't explain though, the first case where ssb-room-client couldn't connect to go-ssb-room, and after a server restart, it could.

**Comment by staltz** [comment]
Downgrading this from this milestone since it's unclear whether (1) is it critical or not, given that most of the time we don't experience this issue, (2) is it specific to go-ssb-room or is it general among ssb-js peers.

**Comment by staltz** [comment]
I can't reproduce this anymore in 21 days, let's call it done. :tada: :taco:
