### ISSUE TITLE
Getting FileNotFoundError when running docker-compose

### ISSUE THREAD

**Issue by minnixtx** [ssb-ngi-pointer/go-ssb-room#264]
New Ubuntu server install on x86-64 machine. See below:

```$ docker-compose build room
Building room
Sending build context to Docker daemon  2.008MB
Step 1/10 : FROM golang:1.16-alpine
 ---> df1795ddbf41
Step 2/10 : RUN apk add --no-cache       build-base       git       sqlite       sqlite-dev
 ---> Using cache
 ---> feafcdf282c5
Step 3/10 : RUN mkdir /app
 ---> Using cache
 ---> 3a0aa3ab5934
Step 4/10 : WORKDIR /app
 ---> Using cache
 ---> ea7c77995940
Step 5/10 : COPY . /app
 ---> Using cache
 ---> 3b0a4376f753
Step 6/10 : RUN cd /app/cmd/server && go build &&     cd /app/cmd/insert-user && go build
 ---> Using cache
 ---> e5468452f0fd
Step 7/10 : EXPOSE 8008
 ---> Using cache
 ---> 78f602f487d1
Step 8/10 : EXPOSE 3000
 ---> Using cache
 ---> cc7d7111e050
Step 9/10 : RUN apk del       build-base       git
 ---> Using cache
 ---> a9abb09d0572
Step 10/10 : CMD ./start.sh
 ---> Using cache
 ---> ee78975da04d
Successfully built ee78975da04d
Successfully tagged go-ssb-room-master_room:latest
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 203, in perform_command
  File "compose/metrics/decorator.py", line 18, in wrapper
  File "compose/cli/main.py", line 380, in build
  File "compose/project.py", line 519, in build
  File "compose/project.py", line 501, in build_service
  File "compose/service.py", line 1133, in build
  File "compose/service.py", line 1948, in build
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp4qa3ljcv'
[4173] Failed to execute script docker-compose
```

**Comment by minnixtx** [comment]
I reinstalled docker and docker-compose and was able to build the room server.
